# Generated by Django 4.0.5 on 2022-06-02 11:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0000'), max_digits=15, null=True),
        ),
    ]
