# Generated by Django 4.0.5 on 2022-06-02 11:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce1', '0002_user_user_type_alter_product_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.00'), max_digits=15, null=True),
        ),
    ]
