# Generated by Django 4.0.5 on 2022-06-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce1', '0003_alter_product_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Eletronics', 'Eletronics'), ('Food', 'Food'), ('Clothes', 'Clothes')], default='CharField', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
