# Generated by Django 4.0.5 on 2022-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce1', '0004_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='if_logged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
