# Generated by Django 4.0.5 on 2022-06-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce1', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='orders_products', to='e_commerce1.product'),
        ),
    ]
